### ISSUE TITLE
Unresolved method/function calls panic

### ISSUE THREAD

**Issue by alexsnaps** [clarkmcc/cel-rust#65]
Could be a regression because of #59 - though looks like the `unwrap()` on the lookup was there before.
Anyways, what led me to start working on #64 is hitting that very problem invoking `bytes()`:

```
panicked at interpreter/src/objects.rs:526:58:
called `Option::unwrap()` on a `None` value
```

Unsure what error should be reported, but panicking isn't certainly not the right thing. I'll look into it

**Comment by clarkmcc** [comment]
I apologize, I'm not sure I totally follow. Is this a new issue introduced by #64? I see that PR introduces an `.unwrap()` call that wasn't there before, but maybe that's not the unwrap that you're referring to? Can you clarify what the problem is and what expression could reproduce it? I'm happy to investigate as well.

**Comment by clarkmcc** [comment]
@alexsnaps thanks for the clarification, makes sense! And I agree with your proposed expected behavior
